cc_binary(
    name = "publisher",
    srcs = ["main.cpp"],
    deps = [
        "//ign_transport_echo_test/proto:echo_cc_proto",
        "//external:ign_msgs",
        "//external:ign_transport",
    ],
)
